technical_processes_search_title: 'Cosa stai cercando?'
technical_processes_search_placeholder: 'Inserire una parola chiave o l''ID del processo'
products_search_title: 'Cosa stai cercando?'
products_search_placeholder: 'Inserire una parola chiave o l''ID del processo'
business_processes_search_title: 'Cosa stai cercando?'
business_processes_search_placeholder: 'Inserire una parola chiave o l''ID del processo'
help_search_title: 'Cosa stai cercando?'
help_search_placeholder: 'Inserire una parola chiave o un termine'
