activity_type_filter: 'Tipo Attività'
document_edited: 'Documento modificato'
document_published: 'Documento pubblicato'
document_shared: 'Documento condiviso'
content_type_filter: 'Tipologia argomento'
product: Prodotti
troubleshooting_article: 'Troubleshooting Articles'
followed_collections: 'Raccolte seguite'
notifications_link_text: Notifiche
unread_notifications_link_text: 'Notifiche non lette'
added_to_collection: 'Documento aggiunto alla raccolta seguita'
