block_title: Download
short_version_button_text: 'Short version'
long_version_button_text: 'Long version'
pdf_disclaimer_text: 'Disclaimer text'
pdf_disclaimer_title: Disclaimer
short_version_filename_prefix: short
long_version_filename_prefix: long
langcode: de
