image: /sites/apprentice/files/pwa/pwa-bg.png
image_small: /sites/apprentice/files/pwa/pwa-bg.pngcopy.png
image_very_small: /sites/apprentice/files/pwa/pwa-bg.pngcopy2.png
site_name: 'Sport- und Gesundheitsförderung'
short_name: 'Sport- und Gesundheit'
description: ''
start_url: /
lang: de
theme_color: '#0298d8'
background_color: '#0298d8'
display: minimal-ui
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
cache_version: '2'
cross_origin: false
langcode: de
offline_page: /offline
skip_waiting: false
