content_type_filter: 'Types de contenu'
product: Produits
business_process: 'Ratio Concept Plus'
technical_process: Processus
troubleshooting_article: 'Articles de dépannage'
other: Autres
filter_help: 'Aide au filtrage'
show_filters: 'Afficher les filtres'
hide_filters: 'Cacher les filtres'
sort_by: 'Sort by'
sort_by_relevance: Pertinence
sort_by_title: Title
search_empty_text: '<p>Désolé, aucun résultat ne correspond à votre recherche.</p><p>Suggestions de recherche : Vérifiez l''orthographe, essayez des mots plus généraux, essayez différents mots qui ont la même signification.</p>'
products_empty_text: '<p>Désolé, aucun résultat ne correspond à votre recherche.</p><p>Suggestions de recherche : Vérifiez l''orthographe, essayez des mots plus généraux, essayez différents mots qui ont la même signification.</p>'
