your_documents_text: 'Vos documents'
manage_account_text: 'Gérer votre compte'
log_out_text: Déconnexion
log_in_text: 'Se connecter'
your_collections_link_text: 'Vos collections'
training_documents_text: 'Documents de formation'
shared_training_documents_text: 'Documents de formation suivis'
