troubleshooting_article_listing_text: 'Vous trouverez ici des informations utiles si la peinture présente déjà un défaut'
product_listing_text: "Ici, vous pouvez rechercher tous les produits RM utilisés pour la réparation des voitures particulières.\r\nVous trouverez les TDS et les MSDS au niveau de l'article.\r\n"
business_process_listing_text: 'Vous trouverez ici tous les procédés utilisés pour rendre l''atelier de carrosserie plus efficace, plus productif et pour optimiser le processus'
technical_process_listing_text: "Découvrez comment utiliser les produits RM et quel processus peut être appliqué\r\n"
technical_processes_search_title: 'Que cherchez-vous ?'
technical_processes_search_placeholder: 'Entrez un mot-clé ou un identifiant de processus'
products_search_title: 'Que cherchez-vous ?'
products_search_placeholder: 'Entrez un mot-clé ou un identifiant de produit'
business_processes_search_title: 'Que cherchez-vous ?'
business_processes_search_placeholder: 'Entrez un mot-clé ou un identifiant de processus'
help_search_title: 'Que cherchez-vous ?'
help_search_placeholder: 'Entrez un mot-clé ou un terme'
