troubleshooting_article_listing_text: 'Hier finden sie hilfreiche Informationen, wenn Sie einen Störung an der lackierten Oberfläche feststellen.'
product_listing_text: "Erfahren Sie, wie Sie mit den Glasurit-Produkten arbeiten und wie Sie sie anwenden können. \r\n\r\nDie technischen Datenblätter und Sicherheitsdatenblätter finden Sie unter den jewiligen Produkten\r\n\r\n"
business_process_listing_text: 'Hier finden Sie einen Prozess, mit dem die Lackiererei effizienter, produktiver und Prozessoptimierender wird'
technical_process_listing_text: 'Erfahren Sie, wie Sie mit den Glasurit-Produkten arbeiten und wie Sie sie anwenden können'
technical_processes_search_title: 'Wonach suchen Sie?'
technical_processes_search_placeholder: 'Geben Sie einen Suchbegriff oder eine Prozess ID ein'
products_search_title: 'Wonach suchen Sie?'
products_search_placeholder: 'Geben Sie ein Suchbegriff oder eine Produkt ID ein'
business_processes_search_title: 'Wonach suchen Sie?'
business_processes_search_placeholder: 'Geben Sie einen Suchbegriff oder eine Prozess ID ein'
help_search_title: 'Wonach suchen Sie?'
help_search_placeholder: 'Geben Sie einen Suchbegriff ein'
