helpfulness_question: 'Was dit artikel nuttig?'
helpfulness_detail_question: 'Kunt u ons wat meer details geven over die feedback?'
feedback_thank_you_message: 'Bedankt voor uw feedback, we zullen dit gebruiken om te verbeteren'
