block_title: 'Добавить в коллекцию'
new_collection_link_text: 'Создать новую коллекцию'
back_link_text: Назад
rename_collection_text: 'Переименовать коллекцию'
share_collection_text: 'Поделиться коллекцией'
delete_collection_text: 'Удалить коллекцию'
download_collection_text: 'Скачать коллекцию'
no_collections_found_text: 'Коллекции не найдены'
collection_download_error_text: 'Коллекция не может быть скачана'
manage_collections_plural_text: 'Управлять коллекциями'
manage_collection_singular_text: 'Управлять коллекцией'
no_items_found_text: 'В коллекции нет файлов'
followed_collections_text: 'Отслеживаемые коллекции'
follow_this_collection_text: 'Вы подписаны на отслеживание коллекции'
delete_collection_confirmation_text: 'Вы уверены, что хотите удалить коллекцию?'
