greeting_name_prefix_text: 'Добрый день,'
your_documents_text: 'Ваши документы'
manage_account_text: 'Управление аккаунтом'
log_out_text: Выйти
log_in_text: Войти
your_collections_link_text: 'Ваши коллекции'
training_documents_text: 'Обучающая документация'
shared_training_documents_text: 'Отслеживание обучающей документации'
