troubleshooting_article_listing_text: 'Здесь Вы можете получить полезную информацию, необходимую при наличии повреждения ЛКП.'
product_listing_text: "Здесь предоставлена информация о всей продукции Glasurit, применяемой для ремонта пассажирского транспорта.\r\nВы получите доступ к технической информации (TDS) и паспортам безопасности (MSDS).\r\n"
business_process_listing_text: 'Информация, необходимая для повышения эффективности и результативности МКЦ, а также оптимизации рабочих процессов.'
technical_process_listing_text: 'Информация о применении и использовании продукции Glasurit.'
technical_processes_search_title: 'Введите слова для поиска:'
technical_processes_search_placeholder: 'Ввести ключевое слово'
products_search_title: 'Введите слова для поиска:'
products_search_placeholder: 'Ввести ключевое слово'
business_processes_search_title: 'Введите слова для поиска:'
business_processes_search_placeholder: 'Ввести ключевое слово'
help_search_title: 'Введите слова для поиска:'
help_search_placeholder: 'Ввести ключевое слово'
