troubleshooting_article_listing_text: 如已出现油漆缺陷，您可以在这里找到有用的信息。
product_listing_text: "您可以在这里搜索用于乘用车修补的所有鹦鹉产品。\r\n您可以在相关文章中找到TDS 和MSDS。\r\n"
business_process_listing_text: 您可以在这里找到用于使修补车间更有效、更有生产力以及优化流程的所有工艺。
technical_process_listing_text: 找出使用鹦鹉产品的方法以及可以使用的工艺。
technical_processes_search_title: 您在寻找什么？
technical_processes_search_placeholder: 输入关键字或工艺ID
products_search_title: 您在寻找什么？
products_search_placeholder: 输入关键字或产品ID
business_processes_search_title: 您在寻找什么？
business_processes_search_placeholder: 输入关键字或工艺ID
help_search_title: 您在寻找什么？
help_search_placeholder: 输入关键字或词语
