activity_type_filter: 活动类型
account_changed: 账户改变
content_type_filter: 内容类型
product: 产品
troubleshooting_article: 故障诊断的文章
business_process: 业务工艺
technical_process: 技术工艺
collection_type_filter: 集合类型
your_collections: 用户集合
followed_collections: 随后集合
apply_filter_button_text: 申请
document_edited: 已编辑文件
document_published: 已通过文件
document_shared: 已分享文件
added_to_collection: 添加到后续收藏的文档
training_document_edit_grant: 您可以编辑的新培训文档
component_edited: 在可编辑培训文档中的组件
notifications_link_text: 通知
unread_notifications_link_text: 未读通知
