block_title: 下载
short_version_button_text: 短文版
long_version_button_text: 长文版
pdf_disclaimer_text: '本出版物所载的数据是基于我们目前的知识和经验。鉴于有许多因素可能影响我们产品的加工和应用，这些数据并不免除加工商自行进行调查和测试的责任；这些数据既不意味着对某些特性的任何保证，也不意味着产品对特定用途的适用性。本网站所提供的任何描述、图片、照片、数据、比例、重量等仅供一般参考；它们可以在没有预先信息的情况下更改，并且不构成产品的约定合同质量(产品规格)。最新版本取代了所有以前的版本。您可以从我们的网站http://techinfo.glasurit.com或直接从您的销售伙伴处获得最新版本。接收我们产品的人有责任确保任何专有权利和现有的法律和法规得到遵。'
