greeting_name_prefix_text: Hej
your_documents_text: 'Mina Dokument'
manage_account_text: 'Hantera ditt konto'
log_out_text: 'Logga ut'
log_in_text: 'Logga in'
your_collections_link_text: 'Mina Samlingar'
training_documents_text: Träningsdokument
