helpfulness_question: 'Var den här artikeln hjälpsam?'
helpfulness_detail_question: 'Kan du ge oss lite mer information om din återkoppling?'
feedback_thank_you_message: 'Tack för din återkoppling, vi strävar alltid efter förbättring!'
