troubleshooting_article_listing_text: 'Här kan du hitta hjälpsam information om det redan är en defekt i lacken'
product_listing_text: "Här kan du söka efter alla Glasuritprodukter som används för personbilsreparationer.\r\nDu kan hitta TDS och MSDS på artikelnivå.\r\n"
business_process_listing_text: 'Här kan du hitta alla processer för ökning av effektivitet, produktivitet och för att optimera processer i verkstaden.'
technical_process_listing_text: 'Få reda på hur man använder Glasuritprodukter och vilka processer som kan appliceras.'
technical_processes_search_title: 'Vad letar du efter?'
technical_processes_search_placeholder: 'Skriv in ett nyckelord eller process-ID'
products_search_title: 'Vad letar du efter?'
products_search_placeholder: 'Skriv in ett nyckelord eller produkt-ID'
business_processes_search_title: 'Vad letar du efter?'
business_processes_search_placeholder: 'Skriv in ett nyckelord eller process-ID'
help_search_title: 'Vad letar du efter?'
help_search_placeholder: 'Skriv in ett nyckelord eller term'
