content_type_filter: 'Content types'
product: Produkt
business_process: 'Ratio Concept Plus'
technical_process: Processes
troubleshooting_article: Felsökningsartikel
other: Others
filter_help: 'Filter Help'
show_filters: 'Show filters'
hide_filters: 'Hide filters'
sort_by: 'Sort by'
sort_by_relevance: Relevance
sort_by_title: Title
sort_by_changed: Changed
