block_title: 'Lägg till i samling'
new_collection_link_text: 'Skapa ny samling'
back_link_text: Tillbaka
rename_collection_text: 'Ändra namn på samling'
share_collection_text: 'Dela samling'
delete_collection_text: 'Ta bort samling'
download_collection_text: 'Ladda ned samling'
no_collections_found_text: 'Ingen samling hittades'
collection_download_error_text: 'Denna samling kan inte laddas ned'
manage_collections_plural_text: 'Hantera samlingar'
manage_collection_singular_text: 'Hantera samling'
no_items_found_text: 'Inga objekt hittades i denna samling'
followed_collections_text: 'Delade Samlingar'
follow_this_collection_text: 'Samling sparad i Delade Samlingar'
delete_collection_confirmation_text: 'Är du säker på att du vill ta bort denna samling'
