business_process_listing_url: /iş-süreçleri
business_process_listing_text: 'Değer Katan Hizmetler'
technical_process_listing_url: /teknik-süreçler
technical_process_listing_text: Süreçler
troubleshooting_article_listing_url: /yardım
troubleshooting_article_listing_text: 'Yardım Merkezi'
product_listing_url: /ürünler
product_listing_text: Ürünler
