greeting_name_prefix_text: 'Witaj,'
your_documents_text: 'Twoje dokumenty'
manage_account_text: 'Zarządzaj kontem'
log_out_text: 'Wyloguj się'
log_in_text: 'Zaloguj się'
your_collections_link_text: 'Twoje kolekcje'
training_documents_text: 'Dokumenty szkoleniowe'
shared_training_documents_text: 'Obserwowane dokumenty szkoleniowe'
