helpfulness_question: 'Czy ten artykuł był pomocny?'
helpfulness_detail_question: 'Czy możemy dowiedzieć się więcej na temat Twoich wrażeń związanych z tym artykułem?'
feedback_thank_you_message: 'Dziękujemy za opinię. Wykorzystamy ją do ulepszenia zawartości.'
