troubleshooting_article_listing_text: 'Here you can find helpful information if there is already a defect in the paint'
product_listing_text: "Here you can search for all Glasurit Products used for Passenger Car repairs.\r\nYou will find the TDS and MSDS on article level.\r\n"
business_process_listing_text: 'Here you can find al process used to make the bodyshop more efficent, productiv and to optimize process'
technical_process_listing_text: 'Find out how to use the Glasurit Products and which process can be applied how'
technical_processes_search_title: 'Cosa stai cercando?'
technical_processes_search_placeholder: 'Inserire una parola chiave o l''ID del processo'
products_search_title: 'Cosa stai cercando?'
products_search_placeholder: 'Inserire una parola chiave o l''ID del prodotto'
business_processes_search_title: 'Cosa stai cercando?'
business_processes_search_placeholder: 'Inserire una parola chiave o l''ID del processo'
help_search_title: 'Cosa stai cercando?'
help_search_placeholder: 'Inserire una parola chiave o un termine'
