activity_type_filter: 'Activity Type'
account_changed: 'Account changed'
content_type_filter: 'Content Type'
business_process: 'Business Process'
technical_process: 'Technical Process'
collection_type_filter: 'Collection Type'
your_collections: 'User Collections'
followed_collections: 'Followed Collections'
