greeting_name_prefix_text: Bem-vindo
your_documents_text: 'Seus documentos'
manage_account_text: 'Gerir conta'
log_out_text: 'Terminar sessão'
log_in_text: 'Iniciar sessão '
your_collections_link_text: 'Suas coleções '
training_documents_text: 'Documentos de formação'
shared_training_documents_text: 'Documentos de formação seguidos'
