terms: "<p>Ho letto e compreso i Termini e le Condizioni</p>\r\n"
data_topics: "<p>Argomenti</p>\r\n"
pending_email_body: 'La tua richiesta per un account è attualmente in attesa di approvazione. '
accepted_email_body: "La tua richiesta è stata accettata.\r\n\r\nAdesso sei in grado di accedere a: https://knowhow.glasurit.com/user/login\r\n\r\nGrazie e divertiti ad esplorare Glasurit Know How!"
rejected_email_body: 'La tua richiesta è stata respinta.'
