content_type_filter: 'Content types'
product: Products
business_process: Services
technical_process: Processes
troubleshooting_article: 'Troubleshooting Articles'
other: Other
show_filters: 'Show filters'
hide_filters: 'Hide filters'
sort_by: 'Sort by'
sort_by_title: Title
sort_by_changed: Changed
