activity_type_filter: 'Activity Type'
document_edited: 'Documento editado'
document_published: 'Documento publicado'
document_shared: 'Documento partilhado'
added_to_collection: 'Documento adicionado na referida coleção'
account_changed: 'Conta modificada'
training_document_edit_grant: 'Novo documento de treino editável '
component_edited: 'Componente editado no documento de treino editável'
content_type_filter: 'Tipo de conteúdo '
product: Produto
business_process: 'Business Process'
technical_process: 'Technical Process'
collection_type_filter: 'Collection Type'
your_collections: 'User Collections'
followed_collections: 'Followed Collections'
