greeting_name_prefix_text: Hallo
your_documents_text: 'Meine Dokumente'
manage_account_text: 'Account verwalten'
log_out_text: Ausloggen
log_in_text: Einloggen
your_collections_link_text: 'Meine Sammlungen'
training_documents_text: Trainingsdokumente
shared_training_documents_text: 'Trainingsdokumente denen Sie folgen'
