block_title: 'Add to collection'
new_collection_link_text: 'Create new collection'
back_link_text: Back
followed_collections_text: 'Followed collections'
follow_this_collection_text: 'Followed this collection'
