terms: '<p>Ich habe die <a href="/de/datenschutzerklaerung">Datenschutzerklärung</a></p> gelesen und verstanden'
data_topics: "<a href=\"/de/rechtlicher-hinweis\">\r\n<p>Disclaimer</p>\r\n"
pending_email_body: 'Ihre Antragstellung für ein Konto steht derzeit noch aus.'
accepted_email_body: 'Ihre Anfrage wurde angenommen.'
rejected_email_body: 'Ihre Anfrage wurde abgelehnt.'
