troubleshooting_article_listing_text: 'Hier vindt u nuttige informatie als er al een defect in de lak zit.'
product_listing_text: "Hier kunt u zoeken naar alle RM-producten die gebruikt worden voor reparaties aan personenauto's.\r\nU vindt de TDS en MSDS op artikelniveau.\r\n"
business_process_listing_text: 'Hier vindt u alle processen die worden gebruikt om het schadeherstelbedrijf efficiënter en productiever te maken en om het proces te optimaliseren.'
technical_process_listing_text: 'Ontdek hoe u de RM-producten kunt gebruiken en welk proces kan worden toegepast.'
technical_processes_search_title: 'Wat zoekt u?'
technical_processes_search_placeholder: 'Voer een trefwoord of proces-ID in '
products_search_title: 'Wat zoekt u?'
products_search_placeholder: 'Voer een trefwoord of product-ID in '
business_processes_search_title: 'Wat zoekt u?'
business_processes_search_placeholder: 'Voer een trefwoord of proces-ID in '
help_search_title: 'Wat zoekt u?'
help_search_placeholder: 'Voer een trefwoord of term in '
