terms: "<p>Ik heb de <a href=\"/nl/privacyverklaring\">voorwaarden en bepalingen gelezen en begrepen</a></p>\r\n"
pending_email_body: 'Uw aanvraag voor een account is momenteel in behandeling.'
accepted_email_body: "Uw aanvraag is geaccepteerd.\r\n\r\nU kunt nu inloggen onder: https://knowhow.glasurit.com/user/login\r\n\r\nBedankt en veel plezier bij het verkennen van Glasurit Know How!"
data_topics: "<p><a href=\"/nl/BENL_disclaimer\">Disclaimer</a></p>\r\n"
