troubleshooting_article_listing_text: 'Aquí encontrarás información útil para cuando haya un defecto en la pintura. '
product_listing_text: "Aquí puedes buscar todos los productos de Glasurit necesarios para usar en los procesos de reparación del turismo. \r\nEncontrarás las Fichas técnicas (TDS) y Fichas de Seguridad a nivel de producto.\r\n"
business_process_listing_text: 'Aquí encontrarás los mejores procesos de pintura para lograr optizimar los procesos y logar un taller más eficiente y productivo. '
technical_process_listing_text: 'Descubra cómo usar los productos Glasurit y en qué procesos poder aplicarlos. '
technical_processes_search_title: '¿Qué estás buscando? '
technical_processes_search_placeholder: 'Introduzca su clave de acceso'
products_search_title: '¿Qué estás buscando? '
products_search_placeholder: 'Introduzca su clave de acceso'
business_processes_search_title: '¿Qué estás buscando? '
business_processes_search_placeholder: 'Introduzca su clave de acceso'
help_search_title: '¿Qué estás buscando? '
help_search_placeholder: 'Introduzca su clave de acceso'
