greeting_name_prefix_text: Hola
your_documents_text: 'Tus Documentos'
manage_account_text: 'Gestiona tu Cuenta'
log_out_text: 'Cerrar Sesión'
log_in_text: 'Iniciar Sesión'
your_collections_link_text: 'Tus colecciones'
training_documents_text: 'Documentos formativos'
shared_training_documents_text: 'Documentos formativos siguientes'
