greeting_name_prefix_text: Ciao
your_documents_text: 'I tuoi documenti'
manage_account_text: 'Gestisci il tuo profilo'
log_out_text: Esci
log_in_text: Accedi
your_collections_link_text: 'Le tue raccolte'
training_documents_text: 'Documenti della Formazione'
shared_training_documents_text: 'Documenti della Formazione seguiti'
