block_title: 'Aggiungi alla raccolta'
new_collection_link_text: 'Crea una nuova raccolta'
back_link_text: Indietro
rename_collection_text: 'Rinomina la raccolta'
share_collection_text: 'Condividi la raccolta'
delete_collection_text: 'Elimina la raccolta'
download_collection_text: 'Scarica la raccolta'
no_collections_found_text: 'Nessuna raccolta trovata'
collection_download_error_text: 'Questa raccolta non può essere scaricata'
manage_collections_plural_text: 'Gestisci le raccolte'
manage_collection_singular_text: 'Gestisci la raccolta'
no_items_found_text: 'Nessun elemento trovato in questa raccolta'
followed_collections_text: 'Raccolte seguite'
follow_this_collection_text: 'Segui questa raccolta'
delete_collection_confirmation_text: 'Sei sicuro di voler eliminare la raccolta?'
