new_training_document_link_text: 'Crea un nuovo documento di formazione'
view_all_training_documents_link_text: 'Visualizza tutti i documenti di formazione'
back_link_text: Indietro
cancel_link_text: Elimina
