helpfulness_question: 'Hai trovato utili queste informazioni?'
helpfulness_detail_question: 'Puoi darci qualche dettaglio in più sulla tua risposta?'
feedback_thank_you_message: 'Grazie per il tuo commento, lo useremo per migliorare'
