greeting_name_prefix_text: 'Добрый день'
your_documents_text: 'Ваши докмуенты'
manage_account_text: 'Управлять аккаунтом'
log_out_text: Выйти
log_in_text: Войти
your_collections_link_text: 'Ваши коллекции'
training_documents_text: 'Обучающие документы'
shared_training_documents_text: 'Обучающие документы, на которые Вы подписаны'
