helpfulness_question: 'Avez-vous trouvé ce module utile ?'
helpfulness_detail_question: 'Pouvez-vous nous donner vos appréciations sur ce module '
feedback_thank_you_message: 'Pouvez-vous nous donner vos appréciations sur ce module '
