block_title: 'Ajouter à la bibliothèque'
new_collection_link_text: 'Create new collection'
back_link_text: Back
rename_collection_text: 'Rename collection'
share_collection_text: 'Share collection'
followed_collections_text: 'Followed collections'
follow_this_collection_text: 'Followed this collection'
