helpfulness_question: '¿Té resulto de gran utlidad este articulo módulo? '
helpfulness_detail_question: '¿Podrías darnos algún comentario para mejorar? '
feedback_thank_you_message: 'Muchas gracias por su comentario. Lo usaremos para mejorar. '
