business_process_listing_url: /business-processes
business_process_listing_text: 'Advanced Business Solutions'
technical_process_listing_url: /technical-processes
technical_process_listing_text: Processes
troubleshooting_article_listing_url: /help
troubleshooting_article_listing_text: 'Help Centre'
product_listing_url: /products
product_listing_text: Products
_core:
  default_config_hash: nUx46YeqlCBip5ueQnKqwgqz1PwcLlzp8KdZlgLAv-A
langcode: de
