block_title: Download
short_version_button_text: Kurzversion
long_version_button_text: Langversion
pdf_disclaimer_text: 'Disclaimer text'
pdf_disclaimer_title: Disclaimer
short_version_filename_prefix: kurz
long_version_filename_prefix: lang
langcode: de
