greeting_name_prefix_text: Hallo
your_documents_text: 'Ihre Dokumente'
manage_account_text: 'Account verwalten'
log_out_text: Ausloggen
log_in_text: 'Log in'
your_collections_link_text: 'Ihre Sammlungen'
training_documents_text: Trainingsdokumente
langcode: de
shared_training_documents_text: 'Followed Training Documents'
