new_training_document_link_text: 'Neues Trainingsdokument erstellen'
view_all_training_documents_link_text: 'Alle Trainingsdokumente anschauen'
back_link_text: Zurück
cancel_link_text: Abbrechen
langcode: de
