activity_type_filter: 'Activity Type'
document_edited: 'Dokument bearbeitet'
document_published: 'Dokument veröffentlicht'
document_shared: 'Dokument geteilt'
added_to_collection: 'Dokument zur folgenden Sammlung hinzugefügt'
account_changed: 'Account geändert'
training_document_edit_grant: 'Neues Trainingsdokument, das Sie bearbeiten können'
content_type_filter: 'Content Type'
component_edited: 'Element in Trainingsdokument geändert, das Sie bearbeiten können'
product: '-'
troubleshooting_article: Produktion
business_process: Labor
technical_process: Applikation
collection_type_filter: 'Collection Type'
your_collections: 'User Collections'
followed_collections: 'Followed Collections'
apply_filter_button_text: Apply
notifications_link_text: Benachrichtigungen
unread_notifications_link_text: 'Ungelesene Benachrichtigungen'
langcode: de
