basf_view_permission: null
view_permission_intro_text: 'Bitte loggen Sie sich ein'
view_permission_button_text: Einloggen
_core:
  default_config_hash: Jv5qN2aYQ6WVFcdA_EGA8pdlxakULjAaGCOIuozYbuY
langcode: de
