notify_ie: !!float -4
notify_firefox: !!float -3
notify_opera: !!float -3
notify_safari: !!float -1
notify_chrome: !!float -3
insecure: true
unsupported: false
mobile: true
position: top
visibility_type: hide
visibility_pages: 'admin/*'
test_mode: false
new_window: false
no_close: true
text_override: ''
reminder: 0
reminder_closed: 168
url: ''
source: ''
show_source: ''
langcode: de
