helpfulness_question: 'War dieser Beitrag hilfreich?'
helpfulness_detail_question: 'Können Sie uns noch mehr Details zu Ihrem Feedback geben?'
feedback_thank_you_message: 'Viel Dank für Ihr Feedback, wir werden diese Informationen zur Verbesserung nutzen'
