business_process_listing_url: /procesy-biznesowe
technical_process_listing_url: /procesy-techniczne
technical_process_listing_text: Procesy
troubleshooting_article_listing_url: /pomoc
troubleshooting_article_listing_text: 'Centrum Pomocy'
product_listing_url: /produkty
product_listing_text: Produkty
business_process_listing_text: Usługi
