new_training_document_link_text: 'Crear un nuevo documento de entrenamiento'
view_all_training_documents_link_text: 'Ver todos los documentos de entrenamiento'
back_link_text: Atrás
cancel_link_text: Cancelar
