greeting_name_prefix_text: Hola
your_documents_text: Documentos
manage_account_text: 'Administrar mi cuenta'
log_out_text: 'Cerrar sesión'
log_in_text: 'Iniciar sesión'
your_collections_link_text: 'Mis colecciones'
training_documents_text: 'Documentos de entrenamiento'
