helpfulness_question: '¿Este articulo fue de ayuda para usted?'
helpfulness_detail_question: '¿Puede brindarnos más detalles de su respuesta?'
feedback_thank_you_message: 'Muchas gracias por sus comentarios, usaremos esto para mejorar'
