troubleshooting_article_listing_text: 'Aquí puede obtener información valiosa si ya existe algún daño en la pintura del vehículo'
product_listing_text: "Aquí podrá encontrar todos los productos Glasurit utilizados para reparación de vehículos de pasajeros. \r\nPodrás encontrar tanto las fichas técnicas como las hojas de seguridad. "
business_process_listing_text: 'Aquí podrá encontrar todos los procesos para aumentar la eficiencia y productividad de su taller y la optimización de procesos.'
technical_process_listing_text: 'Encuentre como utilizar los productos Glasurit y que procesos debe aplicar.'
technical_processes_search_title: '¿Que está buscando?'
technical_processes_search_placeholder: 'Ingrese una palabra clave'
products_search_title: '¿Que está buscando?'
products_search_placeholder: 'Ingrese una palabra clave'
business_processes_search_title: '¿Que está buscando?'
business_processes_search_placeholder: 'Ingrese una palabra clave'
help_search_title: '¿Que está buscando?'
help_search_placeholder: 'Ingrese una palabra clave'
