block_title: 'Añadir a la colección'
new_collection_link_text: 'Crear nueva colección'
back_link_text: Atrás
rename_collection_text: 'Renombrar colección'
share_collection_text: 'Compartir colección'
delete_collection_text: 'Eliminar colección'
download_collection_text: 'Descargar colección'
no_collections_found_text: 'Sin colecciones'
collection_download_error_text: 'Esta colección no puede ser descargada'
manage_collections_plural_text: 'Administrar colecciones'
manage_collection_singular_text: 'Administrar colección'
no_items_found_text: 'Sin items en está colección'
followed_collections_text: 'Colecciones seguidas'
follow_this_collection_text: 'Colección seguida'
delete_collection_confirmation_text: '¿Está seguro que desea eliminar está colección?'
