troubleshooting_article_listing_text: 'Hier finden Sie hilfreiche Informationen, fall ein Lackschaden vorliegt'
product_listing_text: "Hier können Sie nach allen RM-Produkten suchen, die für die Reparatur von Personenkraftwagen verwendet werden.\r\nSie finden das TDS und MSDS auf Artikelebene.\r\n"
business_process_listing_text: 'Hier finden Sie einen Prozess, mit dem die Lackiererei effizienter, produktiver und Prozessoptimierender wird'
technical_process_listing_text: 'Erfahren Sie, wie Sie mit den RM-Produkten arbeiten und wie Sie sie anwenden können'
technical_processes_search_title: 'Wonach suchen Sie?'
technical_processes_search_placeholder: 'Geben Sie einen Suchbegriff oder eine Prozess ID ein'
products_search_title: 'Wonach suchen Sie?'
products_search_placeholder: 'Geben Sie ein Suchbegriff oder eine Produkt ID ein'
business_processes_search_title: 'Wonach suchen Sie?'
business_processes_search_placeholder: 'Geben Sie einen Suchbegriff oder eine Prozess ID ein'
help_search_title: 'Wonach suchen Sie?'
help_search_placeholder: 'Geben Sie einen Suchbegriff oder Stickwort ein'
