troubleshooting_article_listing_text: 'Eğer boya kusurunuz var ise, burada faydalı bilgiler bulabilirsiniz. '
product_listing_text: "Burada binek araçların tamirinde kullanılan bütün RM ürünleri ile ilgili bilgileri bulabilirsiniz. \r\nYazı üzerinde MSDS ve TDS i bulabilirsiniz. "
business_process_listing_text: 'Burada boyahanenizi daha verimli ve üretken yapabilecek ve süreçlerinizi optimize edebilecek bütün bilgilere ulaşabilirsiniz.'
technical_process_listing_text: 'RM ürünlerini nasıl kullanacağınızı ve hangi sürecin nasıl uygulanabileceğini bulabilirsiniz. '
technical_processes_search_title: 'Ne aramıştınız ?'
technical_processes_search_placeholder: 'Lütfen anahtar kelimeleri veya belge kodunu giriniz.'
products_search_title: 'Ne aramıştınız ?'
products_search_placeholder: 'Lütfen anahtar kelimeleri veya belge kodunu giriniz.'
business_processes_search_title: 'Ne aramıştınız ?'
business_processes_search_placeholder: 'Lütfen anahtar kelimeleri veya belge kodunu giriniz.'
help_search_title: 'Ne aramıştınız ?'
help_search_placeholder: 'Lütfen anahtar kelimeleri giriniz'
