block_title: 'Add to collection'
new_collection_link_text: 'Create new collection'
back_link_text: Back
rename_collection_text: 'Rename collection'
share_collection_text: 'Share collection'
delete_collection_text: 'Delete collection'
download_collection_text: 'Download collection'
no_collections_found_text: 'No collections found'
collection_download_error_text: 'This collection cannot be downloaded'
manage_collections_plural_text: 'Manage collections'
manage_collection_singular_text: 'Manage collection'
no_items_found_text: 'No items found in this collection'
followed_collections_text: 'Followed collections'
follow_this_collection_text: 'Follow this collection'
delete_collection_confirmation_text: 'Are you sure you want to delete collection'
