content_type_filter: 'Content types'
product: Product
business_process: 'Business Process'
technical_process: 'Technical Process'
troubleshooting_article: 'Troubleshooting Article'
other: Other
filter_help: 'Filter Help'
show_filters: 'Show filters'
hide_filters: 'Hide filters'
sort_by: 'Sort by'
sort_by_relevance: Relevance
sort_by_title: Title
sort_by_changed: Changed
business_processes_empty_text: '<p>Sorry, no results matched your search.</p><p>Search suggestions: Check your spelling, try more general words, try different words that mean the same thing.</p>'
technical_processes_empty_text: '<p>Sorry, no results matched your search.</p><p>Search suggestions: Check your spelling, try more general words, try different words that mean the same thing.</p>'
help_empty_text: '<p>Sorry, no results matched your search.</p><p>Search suggestions: Check your spelling, try more general words, try different words that mean the same thing.</p>'
search_empty_text: '<p>Sorry, no results matched your search.</p><p>Search suggestions: Check your spelling, try more general words, try different words that mean the same thing.</p>'
products_empty_text: '<p>Sorry, no results matched your search.</p><p>Search suggestions: Check your spelling, try more general words, try different words that mean the same thing.</p>'
