basf_cta: null
_core:
  default_config_hash: co0Kfv7Aystqvno0w8mCbAxh8P-XHbhPxBkUlmJI4S8
product_description: 'Purchase this products'
product_link: 'https://ecommerce.basf-coatings.de/eshop_rms(bD1kZSZjPTEwMA==)/login.htm?sap-params=cGFfbG9nb2s9eA%3d%3d'
