image: /themes/custom/rm/assets/images/icon_512x512px.png
image_small: /themes/custom/rm/assets/images/icon_192x192px.png
image_very_small: /themes/custom/rm/assets/images/icon_144x144px.png
site_name: 'Info R-M'
short_name: 'Info R-M'
description: ''
start_url: /
lang: en
theme_color: '#e6e6e7'
background_color: '#e6e6e8'
display: minimal-ui
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
cache_version: '2'
cross_origin: false
offline_page: /offline
