troubleshooting_article_listing_text: 'Here you can find helpful information if there is already a defect in the paint'
product_listing_text: "Here you can search for all Products used for Passenger Car repairs.\r\nYou will find the TDS and MSDS on article level.\r\n"
business_process_listing_text: 'Here you can find all process used to make the bodyshop more efficent and productive'
technical_process_listing_text: 'Find out how to use the products and which process can be applied how'
