greeting_name_prefix_text: Merhaba
your_documents_text: Belgelerim
manage_account_text: 'Üyeliğini yönet'
log_out_text: Çıkış
log_in_text: Giriş
your_collections_link_text: Koleksiyonlarım
training_documents_text: 'Eğitim dökümanları'
shared_training_documents_text: 'İlgili Eğitim dökümanları'
