helpfulness_question: 'Bu yazı faydalı oldu mu ? '
helpfulness_detail_question: 'Bu yazıdan edindiğiniz deneyim ile ilgili bize geri bildirim verebilir misiniz ? '
feedback_thank_you_message: 'Geri bildiriminiz için teşekkürler. Bunu içeriklerimizi geliştirmek için kullanacağız.'
