block_title: 'Koleksiyona ekle'
new_collection_link_text: 'Yeni koleksiyon oluştur'
back_link_text: Geri
rename_collection_text: 'Koleksiyonu yeniden adlandır'
share_collection_text: 'Koleksiyonu paylaş'
delete_collection_text: 'Koleksiyonu sil'
download_collection_text: 'Koleksiyonu indir'
no_collections_found_text: 'koleksiyon bulunamadı'
collection_download_error_text: 'Bu koleksiyon indirilemez'
manage_collections_plural_text: 'Koleksiyonları Yönet'
manage_collection_singular_text: 'Koleksiyonu yönet'
no_items_found_text: 'Bu koleksiyonda içerik bulunamadı'
followed_collections_text: 'Takip eden koleksiyonlar'
follow_this_collection_text: 'Takip eden koleksiyon'
delete_collection_confirmation_text: 'Bu koleksiyonu silmek istediğinize emin misiniz '
