greeting_name_prefix_text: Hallo
your_documents_text: 'Uw documenten'
manage_account_text: 'Beheer uw account '
log_out_text: 'Log out'
log_in_text: 'Log in'
your_collections_link_text: 'Uw collecties '
training_documents_text: 'Training Documenten'
shared_training_documents_text: 'Gevolgde trainings documenten'
