block_title: 'Toevoegen aan de collectie '
new_collection_link_text: 'Creëer een nieuwe collectie '
back_link_text: 'Terug '
rename_collection_text: 'Hernoem de collectie '
share_collection_text: 'Deelname aan de collectie '
delete_collection_text: 'Verwijder de collectie'
download_collection_text: 'Download de collectie'
no_collections_found_text: 'Geen collecties gevonden'
collection_download_error_text: 'Deze collectie kan niet worden gedownload'
manage_collections_plural_text: 'Collecties beheren'
manage_collection_singular_text: 'Collectie beheren'
no_items_found_text: 'Geen items gevonden in deze collectie'
followed_collections_text: 'Gevolgde collecties'
follow_this_collection_text: 'Deze collectie gevolgd'
delete_collection_confirmation_text: 'Weet u zeker dat u de collectie wilt verwijderen'
