activity_type_filter: 'Type activiteit'
document_edited: 'Bewerkt document'
document_published: 'Document gepubliceerd'
document_shared: 'Gedeelde documenten'
added_to_collection: 'Document toegevoegd aan Gevolgde collectie'
account_changed: 'Account gewijzigd'
training_document_edit_grant: 'Nieuw trainingsdocument dat u kunt bewerken'
component_edited: 'Onderdeel bewerkt in een trainingsdocument dat u kunt bewerken'
content_type_filter: 'Type inhoud'
product: Producten
troubleshooting_article: 'Probleemoplossende Artikelen'
business_process: 'Business Process'
technical_process: 'Technisch Process'
collection_type_filter: 'Type collectie'
your_collections: Gebruikerscollecties
followed_collections: 'Gevolgde collecties'
apply_filter_button_text: Apply
notifications_link_text: Berichten
unread_notifications_link_text: 'Ongelezen berichten'
