helpfulness_question: 'Did you find this article useful?'
helpfulness_detail_question: 'Could you provide us more feedback about your experience with this article'
feedback_thank_you_message: 'Thank you for your feedback, we''ll use this to improve our content.'
