helpfulness_question: '¿Te ha resultado útil este artículo?'
helpfulness_detail_question: '¿Podrías proporcionarnos más ideas/comentarios sobre como mejorar el contenido de este artículo? '
feedback_thank_you_message: 'Muchas gracias por sus comentarios. Estamos trabajando para mejorar.'
