content_type_filter: 'Content type'
product: Products
business_process: 'Programs for Success'
technical_process: Processes
troubleshooting_article: 'Troubleshooting Articles'
other: Others
filter_help: 'Filter Help'
show_filters: 'Show filters'
hide_filters: 'Hide filters'
sort_by: 'Sort by'
sort_by_relevance: Relevance
sort_by_title: Title
sort_by_changed: Changed
