troubleshooting_article_listing_text: 'Descripción de producto'
product_listing_text: 'Listado de producto'
business_process_listing_text: 'Listado procesos de gestión de negocio'
technical_process_listing_text: 'Listado procesos técnicos'
technical_processes_search_title: '¿Qué estas buscando?'
technical_processes_search_placeholder: 'Introducir tu clave de acceso'
products_search_title: '¿Qué estas buscando?'
products_search_placeholder: 'Introducir tu clave de acceso'
business_processes_search_title: '¿Qué estas buscando?'
business_processes_search_placeholder: 'Introducir tu clave de acceso'
help_search_title: '¿Qué estas buscando?'
help_search_placeholder: 'Introducir tu clave de acceso'
