image: /themes/custom/hr/assets/images/icon_512x512px.png
image_small: /themes/custom/hr/assets/images/icon_192x192px.png
image_very_small: /themes/custom/hr/assets/images/icon_144x144px.png
site_name: 'LEAN Online Platform'
short_name: 'LEAN Online Platform'
description: ''
start_url: /
lang: en
theme_color: '#f39602'
background_color: '#f39602'
display: minimal-ui
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
cache_version: '2'
cross_origin: false
offline_page: /offline
