content_type_filter: 'Content types'
product: Products
business_process: Services
technical_process: Processes
troubleshooting_article: 'Troubleshooting Articles'
other: Other
sort_by: 'Sort by'
sort_by_relevance: Relevance
sort_by_title: Title
sort_by_changed: Changed
