troubleshooting_article_listing_text: 'Hier finden sie hilfreiche Informationen, wenn Sie einen Störung an der lackierten Oberfläche feststellen.'
product_listing_text: 'Die technischen Datenblätter und Sicherheitsdatenblätter finden Sie unter den jeweiligen Produkten'
business_process_listing_text: 'Hier finden Sie einen Prozess, mit dem die Lackiererei effizienter, produktiver und Prozessoptimierender wird'
technical_process_listing_text: 'Erfahren Sie, wie Sie mit den Glasurit-Produkten arbeiten und wie Sie sie anwenden können.'
technical_processes_search_title: 'Wonach suchen Sie?'
technical_processes_search_placeholder: 'Suchbegriff(e) eingeben oder Prozess- ID'
products_search_title: 'Wonach suchen Sie?'
products_search_placeholder: 'Suchbegriff(e) eingeben oder Prozess- ID'
business_processes_search_title: 'Wonach suchen Sie?'
business_processes_search_placeholder: 'Suchbegriff(e) eingeben oder Prozess- ID'
help_search_title: 'Wonach suchen Sie?'
help_search_placeholder: 'Geben Sie einen Suchbegriff ein'
