helpfulness_question: 'Finden Sie diesen Artikel hilfreich?'
helpfulness_detail_question: 'Können Sie uns weitere Rückmeldungen zu Ihren Erfahrungen mit diesem Artikel geben?'
feedback_thank_you_message: 'Danke für Ihr Feedback.'
