greeting_name_prefix_text: Hallo
your_documents_text: 'Ihre Dokumente'
manage_account_text: 'Account verwalten'
log_out_text: Logout
log_in_text: Login
your_collections_link_text: 'Ihre Sammlung'
training_documents_text: Trainingsdokumente
shared_training_documents_text: 'Gefolgte Trainingsdokumente'
