helpfulness_question: 'Была ли полезна информация?'
helpfulness_detail_question: 'Пожалуйста, поделитесь своим впечатлением о прочитанной информации. '
feedback_thank_you_message: 'Благодарим за обратную связь. Мы используем её для улучшения модуля.'
