content_type_filter: 'Typy zawartości'
product: Produkt
business_process: 'Proces biznesowy'
technical_process: 'Proces techniczny'
troubleshooting_article: 'Rozwiązywanie problemów'
other: Inne
filter_help: 'Filtr treści'
show_filters: 'Pokaż filtry'
hide_filters: 'Ukryj filtry'
sort_by: 'Sortuj według'
sort_by_relevance: Trafność
sort_by_title: Tytuł
sort_by_changed: Zmiana
search_empty_text: '<p>Brak wyników powiązanych z szukanym hasłem.</p><p>Sugestie wyszukiwania: sprawdź pisownię, spróbuj użyć bardziej ogólnych pojęć lub wyrazów bliskoznacznych.</p>'
products_empty_text: '<p>Brak wyników powiązanych z szukanym hasłem.</p><p>Sugestie wyszukiwania: sprawdź pisownię, spróbuj użyć bardziej ogólnych pojęć lub wyrazów bliskoznacznych.</p>'
business_processes_empty_text: ''
technical_processes_empty_text: ''
help_empty_text: ''
