troubleshooting_article_listing_text: 'Tutaj znajdziesz wsparcie, jeśli powłoka już jest uszkodzona.'
product_listing_text: "Tu możesz wyszukiwać wszystkie produkty Glasurit do napraw pojazdów osobowych.\r\nW poszczególnych artykułach znajdziesz karty techniczne i karty charakterystyki chemicznej.\r\n"
business_process_listing_text: 'Tutaj znajdziesz wszystkie procesy zwiększające wydajność i produktywność oraz optymalizujące pracę w warsztacie.'
technical_process_listing_text: 'Dowiedz się, jak korzystać z produktów Glasurit i jak stosować poszczególne procesy.'
technical_processes_search_title: 'Czego szukasz?'
technical_processes_search_placeholder: 'Wprowadź hasło, którego szukasz lub identyfikator procesu.'
products_search_title: 'Czego szukasz?'
products_search_placeholder: 'Wprowadź hasło, którego szukasz lub identyfikator produktu.'
business_processes_search_title: 'Czego szukasz?'
business_processes_search_placeholder: 'Wprowadź hasło, którego szukasz lub identyfikator procesu.'
help_search_title: 'Czego szukasz?'
help_search_placeholder: 'Wprowadź hasło lub pojęcie którego szukasz.'
