block_title: 'Dodaj do kolekcji'
new_collection_link_text: 'Utwórz nową kolekcję'
back_link_text: Wróć
rename_collection_text: 'Zmień nazwę kolekcji'
share_collection_text: 'Udostępnij kolekcję'
delete_collection_text: 'Usuń kolekcję'
download_collection_text: 'Pobierz kolekcję'
no_collections_found_text: 'Nie znaleziono kolekcji'
collection_download_error_text: 'Tej kolekcji nie można pobrać'
manage_collections_plural_text: 'Zarządzaj kolekcjami'
manage_collection_singular_text: 'Zarządzaj kolekcją'
no_items_found_text: 'Brak elementów w tej kolekcji'
followed_collections_text: 'Obserwowane kolekcje'
follow_this_collection_text: 'Obserwowałem tę kolekcję'
delete_collection_confirmation_text: 'Czy na pewno usunąć kolekcję?'
