block_title: 'Lisää kokoelmaan'
new_collection_link_text: 'Luo uusi kokoelma'
back_link_text: Takaisin
rename_collection_text: 'Nimeä kokoelma uudelleen'
share_collection_text: 'Jaa kokoelma'
delete_collection_text: 'Poista kokoelma'
download_collection_text: 'Lataa kokoelma'
no_collections_found_text: 'Kokoelmia ei löydy'
collection_download_error_text: 'Tämä kokoelma ei ole ladattavissa'
manage_collections_plural_text: 'Hallitse kokoelmia'
manage_collection_singular_text: 'Hallitse kokoelmaa'
no_items_found_text: 'Tuotteita ei löytynyt tästä kokoelmasta'
followed_collections_text: 'Seuratut kokoelmat'
follow_this_collection_text: 'Seuraa tätä kokoelmaa'
delete_collection_confirmation_text: 'Oletko varma että haluat poistaa tämän kokoelman'
