troubleshooting_article_listing_text: 'Täältä löydät hyödyllistä tietoa maalausvirheisiin'
product_listing_text: "Täältä löydät kaikki Glasurit tuotteet joita käytetään henkilöauto maalauksissa.\r\nLöydät TDS ja MSDS dokumentit artikkelitasolta.\r\n"
business_process_listing_text: 'Täältä löydät kaikki toimenpiteet, joilla voidaan parantaa maalaamosi kannattavuutta ja prosessia sekä optimoida työnkulkua.'
technical_process_listing_text: 'Täällä kerromme kuinka Glasurit tuotteita käytetään ja miten niitä ruiskutetaan'
technical_processes_search_title: 'Mitä olet etsimässä?'
technical_processes_search_placeholder: 'Anna avainsana tai prosessin ID'
products_search_title: 'Mitä olet etsimässä?'
products_search_placeholder: 'Anna avainsana tai prosessin ID'
business_processes_search_title: 'Mitä olet etsimässä?'
business_processes_search_placeholder: 'Anna avainsana tai prosessin ID'
help_search_title: 'Mitä olet etsimässä?'
help_search_placeholder: 'Anna avainsana tai termi'
