greeting_name_prefix_text: Hei
your_documents_text: Asiakirjat
manage_account_text: 'Hallinnoi tilisi tekstiä'
log_out_text: 'Kirjaudu ulos'
log_in_text: 'Kirjaudu sisään'
your_collections_link_text: Kokoelmat
training_documents_text: Koulutusasiakirjat
shared_training_documents_text: 'Seuratut koulutusasiakirjat'
