helpfulness_question: 'Piditkö tätä artikkelia hyödyllisenä?'
helpfulness_detail_question: 'Antaisitko enemmän palautetta ja omia kokemuksia tästä artikkelista?'
feedback_thank_you_message: 'Kiitos palautteesta, käytämme palautettasi parantaaksemme sisältöä.'
