business_process_listing_url: '/liiketoiminta- prosessit'
business_process_listing_text: 'Edistyneet liiketoiminnan tukipalvelut'
technical_process_listing_url: '/tekniset prosessit'
technical_process_listing_text: Prosessit
troubleshooting_article_listing_url: /apua
troubleshooting_article_listing_text: Palvelukeskus
product_listing_url: /tuotteet
product_listing_text: Tuotteet
