content_type_filter: 'Type de contenu'
product: Produits
technical_process: Procédés
troubleshooting_article: 'Articles avec défauts '
other: 'Autres '
filter_help: 'Filtre d''aide '
show_filters: 'Afficher les filtres'
hide_filters: 'Masquer les filtres '
sort_by: 'Trier par '
sort_by_relevance: 'Pertinence '
sort_by_title: Titre
sort_by_changed: Changé
