activity_type_filter: 'Type d''activité '
product: Produicts
troubleshooting_article: 'Article avec des défauts '
followed_collections: 'Collections suivies '
document_edited: 'Document Edité'
document_published: 'Document publié '
document_shared: 'Document partagé'
added_to_collection: 'Document ajouté à la collection '
account_changed: 'Compte changé'
training_document_edit_grant: 'Nouveau document de formation que vous pouvez éditer '
content_type_filter: 'Type de contenu '
component_edited: 'Information éditée dans un programme de formation que vous pouvez éditer '
business_process: 'Procédé d''affaires '
technical_process: 'Procédé technique'
collection_type_filter: 'Type de collection '
your_collections: 'Collections de l''utilisateur '
apply_filter_button_text: 'Appliquer '
unread_notifications_link_text: ' Notifications non lues '
