block_title: 'Ajouter à la collection '
new_collection_link_text: 'Créer une nouvelle collection'
back_link_text: 'Retour '
rename_collection_text: 'Renommer une collection '
share_collection_text: 'Partager une collection'
delete_collection_text: 'Supprimer une collection'
download_collection_text: 'Télécharger une collection'
no_collections_found_text: 'Aucune collection n''a été trouvée'
collection_download_error_text: 'Cette collection ne pas être téléchargée'
manage_collections_plural_text: 'Gérer les collections'
manage_collection_singular_text: 'Gérer les collections'
no_items_found_text: 'Aucun élément trouvé dans cette collection'
followed_collections_text: 'Collections à suivre '
follow_this_collection_text: 'Suivre cette collection'
delete_collection_confirmation_text: 'Etes vous sur de vouloir supprimer cette ollection'
