greeting_name_prefix_text: Bonjour
your_documents_text: 'Vos Documents'
manage_account_text: 'Gérer votre compte'
log_out_text: Deconnexion
log_in_text: Connexion
your_collections_link_text: 'Vos Collections'
training_documents_text: 'Documents de formation'
shared_training_documents_text: 'Documents de formation suivis'
