troubleshooting_article_listing_text: 'Vous trouverez ici des informations utiles s''il y a déjà un défaut dans la peinture'
product_listing_text: "Vous pouvez rechercher ici tous les produits ColorSystem utilisés pour la réparation des voitures de tourisme.\r\nVous trouverez les FT et FDS au niveau des articles.\r\n"
business_process_listing_text: 'Vous trouverez ici tous les procédés utilisés pour rendre l''atelier de carrosserie plus efficace, plus productif et pour optimiser les processus'
technical_process_listing_text: 'Découvrez comment utiliser les produits Colorsystem et quel procédé peut être appliqué comment'
technical_processes_search_title: 'Que recherchez-vous ?'
technical_processes_search_placeholder: 'Entrer un mot clé ou un identifiant de processus'
products_search_title: 'Que recherchez-vous ?'
products_search_placeholder: 'Entrez un mot clé ou un ID produit'
business_processes_search_title: 'Que recherchez-vous ?'
business_processes_search_placeholder: 'Entrer un mot clé ou un identifiant de processus'
help_search_title: 'Que recherchez-vous ?'
help_search_placeholder: 'Entrer un mot clé '
