image: /themes/custom/glasurit/assets/images/icon_512x512px.png
image_small: /themes/custom/glasurit/assets/images/icon_192x192px.png
image_very_small: /themes/custom/glasurit/assets/images/icon_144x144px.png
site_name: 'Glasurit Know How International'
short_name: 'Glasurit Know How'
description: ''
start_url: /
lang: en
theme_color: '#193151'
background_color: '#193151'
display: minimal-ui
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
cache_version: '2'
cross_origin: false
offline_page: /offline
skip_waiting: false
