greeting_name_prefix_text: Hola
your_documents_text: 'Tus Documentos'
manage_account_text: 'Gestiona tu cuenta'
log_out_text: Salir
log_in_text: Entrar
your_collections_link_text: 'Tus Colecciones'
training_documents_text: 'Documentos formativos'
shared_training_documents_text: 'Siguientes Documentos formativos'
