block_title: 'Añadir a la Colección'
new_collection_link_text: 'Crear nueva Colección'
back_link_text: Atrás
rename_collection_text: 'Renombrar Colección'
share_collection_text: 'Compartir Colección'
delete_collection_text: 'Borrar Colección'
download_collection_text: 'Descargar Colección'
no_collections_found_text: 'No hay Colección encontrada'
collection_download_error_text: 'Esta Colección no  puede descargarse'
manage_collections_plural_text: 'Gestionar Colecciones'
manage_collection_singular_text: 'Gestionar Colección'
no_items_found_text: 'No se han encontrado estos puntos en la Colección'
followed_collections_text: 'Siguiente Colección'
follow_this_collection_text: 'Seguir esta Colección'
delete_collection_confirmation_text: 'Estas seguro de que quieres borrar esta Colección'
