business_process_listing_url: /business-processes
business_process_listing_text: 'Servicios'
technical_process_listing_url: /technical-processes
technical_process_listing_text: Procesos
troubleshooting_article_listing_url: /help
troubleshooting_article_listing_text: 'Centro de ayuda'
product_listing_url: /products
product_listing_text: Productos
