image: /sites/colorsystem/files/pwa/Favicon.png
image_small: /sites/colorsystem/files/pwa/Favicon.pngcopy.png
image_very_small: /themes/custom/colorsystem/assets/images/icon_144x144px.png
site_name: 'ColorSystem Paint'
short_name: ColorSystem
description: ''
start_url: /
lang: en
theme_color: '#193151'
background_color: '#193151'
display: minimal-ui
default_image: '0'
urls_to_cache: ''
urls_to_exclude: "admin/.*\r\nuser/.*"
cache_version: '2'
cross_origin: false
offline_page: /offline
skip_waiting: false
