account: basf
profile: eccolorsystem
environment: dev
tag_load: async
sync_load_position: top
api_only: true
defaults_everywhere: true
defer_fields: false
json_encoded: dru
_core:
  default_config_hash: I1c1R8FOoq-yrcNnHP9-0fmXYp8KG7PlLeVxkVsS1SA
